### ISSUE TITLE
2023 production milestone

### ISSUE THREAD

**Issue by danneu** [danneu/guild#203]
I'm updating the guild after years of inactivity and accumulating changes at <https://test.roleplayerguild.com>.

There are some thing I want to do (and then test) before I deploy.

## Checklist

- [x] Merge LegendBegins' fixes
- [x] Fix asset building
    - Before, there was a weird process where I'd check out a "production" branch, build assets, and commit them there but that's kinda pointless. Now I just compile a `dist` folder and if it exists, then the serves it. It's simpler and code is updated to modern gulp.
- [ ] Update deps 
- [ ] Test critical forum functions on <https://test.roleplayerguild.com>
- [ ] Figure out / improve deploy step
- [ ] Fix `/discord`

## General wishlist

- Refactor asset compilation
- Bump ancient deps including Node (Guild was using Node v8.0)
- Remove deps or bring them into the codebase
    - For a project that isn't touched very often, updating deps is painful. In the Javascript ecosystem, major version changes on a library are more likely to reflect pointless changes (like moving from `require('lib')` to `import x from 'lib'`) rather than code improvements.
- Create new deploy step
    - I don't remember much about the old deploy step, and the tool I was using (shipit) is now defunct. I only remember I was using pm2/monit on the prod server. Need to get deployments working again and potentially polish it.
- Backup database
    - I think this entails upgrading postgres (AWS RDS) as well. 
- Shrink EC2 server
    - The prod server is way too big (expensive) for the load.

**Comment by danneu** [comment]
Ended up deploying and dropping the test subdomain. gonna push things live until there's something that needs more testing like maybe the bbcode changes.
